### ISSUE TITLE
Unable to Use Field Type in Group

### ISSUE THREAD

**Issue by peterson-umoke** [rubengc/cmb2-field-animation#1]
Hello There, I tried seeing if i could use your field type in a group and it didnt save the data i inserted, can you help?

here is code block:
`$cmb = new_cmb2_box(array(
            'id' => $this->prefix . 'bookingbox',
            'title' => esc_html__('Movie Booking Configurations', $this->locale),
            'object_types' => $this->attached_post_type, // Post type
            'priority' => 'high',
            'context' => 'normal',
            'show_names' => true, // Show field names on the left
            'classes' => 'gidi-movies-bookingbox', // Extra cmb2-wrap classes
            'show_in_rest' => WP_REST_Server::ALLMETHODS // allows this metabox to be visible in the rest api
        ));

$bc_movie_id = $cmb->add_field(array(
            'id' => $this->prefix . 'booking_configuration',
            'type' => 'group',
            'repeatable' => true,
            'options' => array(
                'group_title' => 'Booking Configuration {#}',
                'add_button' => 'Add Another Booking Configuration',
                'remove_button' => 'Remove This Booking Configuration',
                'closed' => false,  // Repeater fields closed by default - neat & compact.
                'sortable' => true,  // Allow changing the order of repeated groups.
            ),
        ));

$cmb->add_group_field($bc_movie_id, array(
            'name' => __('Test Animation', 'cmb2'),
            'desc' => __('Field description (optional)', 'cmb2'),
            'id' => $prefix . '_animation',
            'type' => 'animation',
            // 'groups'        => array( 'entrances', 'exits' ), // By default all groups are enabled
            'preview' => true // "Preview" text where animations are applied after change
        ));`

**Comment by rubengc** [comment]
Hi @peterson-umoke 

I just closed this issue since I can't reproduce it, anyway, check the new version of this field (1.0.2) that I will release in a few minutes
